/**
 * Marketing reel for the logged-out hero.
 *
 * Every number here is AUTHORED, not computed. The hero is illustrative
 * content for people who have not connected a league yet, so it must never
 * run pricing logic: the widgets step through these frames and format them,
 * nothing more.
 *
 * The numbers are still held to the engine's own arithmetic, because a
 * sportsbook that quotes an impossible price is not a sportsbook:
 *
 * - Every matchup frame is a FAIR two-way market. `probToAmerican` in
 *   server/engine/engine.js makes the two sides exact mirrors (61.4% is
 *   -159 and 38.6% is +159), so a hero showing -159 against +134 would be
 *   quoting 104.1% of book, i.e. 4.1 points of vig we do not charge and do
 *   not model. Each pair below was generated from that function.
 * - Acceptance band words are not written here at all; they are read from
 *   src/utils/acceptanceLingo.ts when the card renders.
 */

export interface LineFrame {
  you: { team: string; prob: number; moneyline: number };
  them: { team: string; prob: number; moneyline: number };
  /** Move in win probability from the previous frame, authored alongside it. */
  move: number;
  note: string;
}

/**
 * A fair two-way market drifting through a week.
 *
 * The notes are the engine's OWN trigger vocabulary, the same strings it
 * writes into line history: opening board, projection refresh, waiver run,
 * lineup change. They used to be invented injury beats ("Their QB ruled out",
 * "Nacua downgraded to questionable"), which read as writing rather than as a
 * product, and described a feed we do not have. These are the four things
 * that actually move a line here.
 */
export const LINE_FRAMES: LineFrame[] = [
  {
    you: { team: "Zeus's Bolts", prob: 58.2, moneyline: -139 },
    them: { team: 'Hermes Express', prob: 41.8, moneyline: 139 },
    move: 0,
    note: 'Opening board',
  },
  {
    you: { team: "Zeus's Bolts", prob: 61.4, moneyline: -159 },
    them: { team: 'Hermes Express', prob: 38.6, moneyline: 159 },
    move: 3.2,
    note: 'Projection refresh',
  },
  {
    you: { team: "Zeus's Bolts", prob: 59.6, moneyline: -148 },
    them: { team: 'Hermes Express', prob: 40.4, moneyline: 148 },
    move: -1.8,
    note: 'Waiver run',
  },
  {
    you: { team: "Zeus's Bolts", prob: 63.0, moneyline: -170 },
    them: { team: 'Hermes Express', prob: 37.0, moneyline: 170 },
    move: 3.4,
    note: 'Lineup change',
  },
];

export interface TradeFramePlayer {
  name: string;
  position: string;
  /** Sleeper id. The page turns it into a proxied headshot URL through
      apiUrl, because a baked absolute path does not resolve in the native
      shell, where the app and the server sit on different origins. */
  sleeperId: string | null;
}

/**
 * Shape only. The trades themselves live in ./landingTrades.ts and are
 * GENERATED by scripts/generate-landing-trades.mjs, which runs the real
 * suggestTrades from server/engine/engine.js over a league drafted from the
 * 2026 projection sheets.
 *
 * They used to be written by hand here, and every one of them was wrong. The
 * worst sent Derrick Henry for Puka Nacua and Trey McBride, which moves 222
 * points of projection across the table in my favour with Nacua alone
 * out-projecting Henry. Authoring a trade means guessing at player value, and
 * there is an engine in this repo whose entire job is not guessing.
 */
export interface TradeFrame {
  partner: string;
  send: TradeFramePlayer[];
  get: TradeFramePlayer[];
  /** Priced by the engine's acceptanceProbability, not chosen. */
  acceptance: number;
  youTitleDelta: number;
  partnerTitleDelta: number;
}
