import { useEffect, useId, useRef, useState, type ReactNode } from 'react';
import './Gloss.css';

const GLOSSES = {
  ppr: {
    label: 'PPR',
    body: 'Point Per Reception. Each catch is worth 1 fantasy point on top of yardage and TDs. Most modern fantasy leagues use PPR or Half-PPR.',
  },
  'o-u': {
    label: 'O/U',
    body: "Over/Under. The total combined points oddsmakers expect both NFL teams to score in a game. Used here to gauge how much offense to expect for a player's matchup.",
  },
  delta: {
    label: 'Delta',
    body: 'Delta. The change in your win probability if you make a given lineup move.',
  },
  moneyline: {
    label: 'Moneyline',
    body: 'Sportsbook odds expressing the favorite and underdog. -220 means favored: risk $220 to win $100. +180 means underdog: risk $100 to win $180.',
  },
  spread: {
    label: 'Spread',
    body: "The expected margin of victory. -14.2 means you're favored to win by 14.2 points. Negative is favored, positive is underdog.",
  },
  baseline: {
    label: 'Baseline',
    body: "The pricing model's starting state, before any lineup changes you make. Click a SWAP row to see how it shifts.",
  },
  'line-if-started': {
    label: 'Line if started',
    body: 'What your matchup moneyline becomes if you start this player instead of your current starter at the slot.',
  },
  pivot: {
    label: 'Pivot',
    body: 'A starter slot the model has flagged for a potential change.',
  },
  swap: {
    label: 'Swap',
    body: 'A bench player would meaningfully improve your win probability if started over your current pick at this slot.',
  },
  'tight-call': {
    label: 'Tight call',
    body: 'Your starter is the right pick, but the gap between them and a bench alternative is small. Worth keeping an eye on.',
  },
  projection: {
    label: 'Projection',
    body: "Expected fantasy points this week, generated by the simulation engine across 10,000 iterations of the player's matchup.",
  },
  'win-prob': {
    label: 'Win prob',
    body: "The simulation engine's estimate of your probability of winning this week's matchup, given your current lineup.",
  },
};

export type GlossTerm = keyof typeof GLOSSES;

interface GlossProps {
  term: GlossTerm;
  children: ReactNode;
}

export function Gloss({ term, children }: GlossProps) {
  const gloss = GLOSSES[term];
  const id = useId();
  const triggerRef = useRef<HTMLSpanElement | null>(null);
  const hoverTimerRef = useRef<number | null>(null);
  const [isOpen, setIsOpen] = useState(false);
  const [placement, setPlacement] = useState<'above' | 'below'>('below');

  useEffect(() => {
    if (!isOpen) {
      return undefined;
    }

    const handleKeyDown = (event: KeyboardEvent) => {
      if (event.key === 'Escape') {
        setIsOpen(false);
      }
    };

    document.addEventListener('keydown', handleKeyDown);

    return () => {
      document.removeEventListener('keydown', handleKeyDown);
    };
  }, [isOpen]);

  const updatePlacement = () => {
    const triggerRect = triggerRef.current?.getBoundingClientRect();
    setPlacement(triggerRect && window.innerHeight - triggerRect.bottom < 160 ? 'above' : 'below');
  };

  const openWithDelay = () => {
    if (hoverTimerRef.current !== null) {
      window.clearTimeout(hoverTimerRef.current);
    }

    hoverTimerRef.current = window.setTimeout(() => {
      updatePlacement();
      setIsOpen(true);
    }, 200);
  };

  const close = () => {
    if (hoverTimerRef.current !== null) {
      window.clearTimeout(hoverTimerRef.current);
      hoverTimerRef.current = null;
    }

    setIsOpen(false);
  };

  return (
    <span
      className={['gloss', isOpen ? 'gloss--open' : '', `gloss--${placement}`]
        .filter(Boolean)
        .join(' ')}
      onMouseLeave={close}
    >
      <span
        aria-describedby={isOpen ? id : undefined}
        className="gloss__trigger"
        onBlur={close}
        onFocus={() => {
          updatePlacement();
          setIsOpen(true);
        }}
        onMouseEnter={openWithDelay}
        ref={triggerRef}
        tabIndex={0}
      >
        {children}
      </span>
      {isOpen ? (
        <span className="gloss__tooltip" id={id} role="tooltip">
          <span className="gloss__label">{gloss.label}</span>
          <span className="gloss__body">{gloss.body}</span>
        </span>
      ) : null}
    </span>
  );
}
